services:
  - type: web
    name: vsbec-feedback-system
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:asgi_app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: HOD_USERNAME
        sync: false
      - key: HOD_PASSWORD
        sync: false
      - key: ENCRYPTION_SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
